name: Global Flutter Factory
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Initialize and Build
        run: |
          # إنشاء مشروع جديد مؤقت لضمان وجود كافة ملفات الأندرويد
          flutter create --project-name factory_app --org com.ruqi.factory . --force
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ruqi-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
